import { Button, VerticalBox, HorizontalBox, StandardListView } from "std-widgets.slint";

export AppWindow := Window {
    property<int> counter: 42;
    property<bool> undoPossible: false;
    property<[StandardListViewItem]> model;
    callback request-increase-value();
    callback request-undo();
    HorizontalBox {
        VerticalBox { 
            Text {
                text: "Counter: \{counter}";
            }
            Button {
                text: "Increase value";
                clicked => { 
                    request-increase-value();
                }
            }
            Button {
                text: "Undo";
                enabled: undoPossible;
                clicked => { 
                    request-undo();
                }
            }
        }
        VerticalBox {
            Text {
                text: "Undo Stack";
            } 
            UndoStackView := StandardListView {
                width: 200px;
                model <=> root.model;

            }
        }
    }
}
